est-api-autoec-BRANCH:
  image: IMAGE
  entrypoint: java -Xms512m -Xmx512m -XX:+UseParallelGC -jar est-api-autoec.jar
  environment:
    - SPRING_PROFILES_ACTIVE=staging
# Antes de alterar pergunte para o time de infra
  labels:
    aplicacao: est-api-autoec-BRANCH
    io.rancher.scheduler.affinity:host_label: api_nova=true
    io.rancher.container.pull_image: always
