---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: CONTAINER_NAME-mapping
  namespace: CONTAINER_NAME
spec:
  prefix: /est-api-autoec-ENVIRONMENT/
  service: CONTAINER_NAME-service.CONTAINER_NAME:8080

---
kind: Service
apiVersion: v1
metadata:
  name: CONTAINER_NAME-service
spec:
  selector:
    app: CONTAINER_NAME
  ports:
     - port: 8080
  type: ClusterIP
     
---
apiVersion: apps/v1           # API version
kind: Deployment   
metadata:
  name: METADATA   
  labels:                    
    app: CONTAINER_NAME
spec:
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1                  
  selector:
    matchLabels:             
      app: CONTAINER_NAME
  template:                  
    metadata:
      labels:                
        app: CONTAINER_NAME
    spec:     
      imagePullSecrets:
      - name: macdevcr
      containers:
      - name: CONTAINER_NAME
        image: IMAGE
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ENVIRONMENT  
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 450Mi
        ports:
        - containerPort: 8080
          name: 8080tcp2
          protocol: TCP
        stdin: true
        tty: true
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1