est-api-autoec-BRANCH:
  scale: 1
  start_on_create: true
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    recreate_on_quorum_strategy_config:
      quorum: 1
    port: 8080
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreateOnQuorum
    request_line: GET "/actuator/health" "HTTP/1.0"
    reinitializing_timeout: 60000